const contact = <><strong>Employ AI, an S corporation, doing business as The Blue Dot Agency</strong><br/>Las Vegas, Nevada<br/>Phone: <a href="tel:+17022921451">702-292-1451</a><br/>Email: <a href="mailto:team@thebluedotagency.com">team@thebluedotagency.com</a></>;
const Section = ({title, children}) => <section><h2>{title}</h2>{children}</section>;
const Bullets = ({children}) => <ul>{children}</ul>;

function PrivacyPolicy(){return <>
  <p className="legal-kicker">Effective Date: September 3, 2026</p><h1>Privacy Policy</h1>
  <p className="legal-lead">Employ AI, an S corporation doing business as The Blue Dot Agency, operates this website. This notice explains what we collect, why we collect it, the services that help us operate the site, and the choices available to you.</p>
  <Section title="1. Information We Collect"><Bullets><li>Contact and inquiry information, such as your name, email address, phone number, company, and messages you send us.</li><li>Appointment information and communication preferences submitted through our booking provider.</li><li>Chat content and related interaction records when you choose to use the website chat.</li><li>Technical and usage information, such as IP address, browser, device, referring page, pages viewed, and interaction data.</li><li>Consent, opt-in, opt-out, and communication records.</li></Bullets><p>Please do not submit sensitive personal information, health information, financial account credentials, government identification numbers, or emergency information through the website chat or booking form.</p></Section>
  <Section title="2. How We Use Information"><Bullets><li>Respond to inquiries and schedule conversations.</li><li>Provide requested services and communicate about appointments.</li><li>Operate, secure, troubleshoot, and improve the website.</li><li>Understand website use when you permit analytics.</li><li>Maintain consent and opt-out records and meet legal obligations.</li></Bullets></Section>
  <Section title="3. AI-Assisted Chat and Automation"><p>Our website chat may use artificial intelligence and automated tools to provide initial responses, route inquiries, and assist with scheduling. You are interacting with an automated system unless a team member joins the conversation. AI responses may be incomplete or inaccurate and are not professional, legal, medical, financial, or emergency advice.</p><p>Chat content may be processed and stored by LeadConnector or GoHighLevel and their service providers so the chat can operate, conversations can be reviewed, and our team can respond. Do not use the chat for emergencies. If you or someone else may be in immediate danger, contact local emergency services.</p></Section>
  <Section title="4. Service Providers and Data Flows"><p>We use service providers to operate this website. They process information for us under their own terms and privacy commitments:</p><Bullets><li><strong>LeadConnector and GoHighLevel:</strong> appointment booking, website chat, customer relationship management, email, and SMS communication.</li><li><strong>Microsoft Clarity:</strong> website interaction and session analytics, loaded only after you allow analytics and chat.</li><li><strong>Plausible Analytics:</strong> website traffic measurement, loaded only after you allow analytics and chat.</li><li><strong>Cloudflare and OpenAI Sites:</strong> website delivery, security, and hosting infrastructure.</li></Bullets><p>We do not sell or rent personal information. We may disclose information when required by law, to protect rights and safety, or as part of a business transfer subject to appropriate safeguards.</p></Section>
  <Section title="5. Cookies and Your Choice"><p>Essential hosting and security technologies may operate when you visit. Analytics and the AI-assisted chat widget load only after you select “Allow analytics and chat.” You may choose “Essential only” and still view the website and use the direct booking links. You can reopen Privacy choices from the footer and change your selection at any time. Changing your selection affects future loading on that device and does not automatically delete information already collected.</p></Section>
  <Section title="6. SMS and Email Communications"><p>We send marketing text messages only with the consent collected for that purpose. Consent to receive marketing messages is not a condition of purchase. Message frequency varies and message and data rates may apply. Reply STOP to stop text messages or HELP for assistance. Use the unsubscribe link in a marketing email to stop marketing email. Service and appointment messages may still be sent when necessary to fulfill your request.</p><p>Mobile opt-in data and consent records are not sold or shared with third parties for their own marketing. They may be provided to messaging vendors solely to deliver the communications you requested.</p></Section>
  <Section title="7. Retention and Deletion"><p>We retain information only for as long as reasonably necessary for the purpose described in this notice, to provide services, maintain consent and opt-out records, resolve disputes, secure our systems, and meet tax, accounting, contractual, or legal requirements. Retention varies by record type and our relationship with you. When information is no longer required, we delete or de-identify it, subject to limited backup, fraud-prevention, and legal-hold exceptions.</p><p>You may request access, correction, or deletion by emailing <a href="mailto:team@thebluedotagency.com?subject=Privacy%20request">team@thebluedotagency.com</a>. We may need to verify your identity and may retain information where permitted or required by law. We will also communicate qualifying requests to applicable service providers.</p></Section>
  <Section title="8. Nevada Privacy Rights"><p>Nevada residents may submit a verified request concerning covered information and may direct us not to make a covered sale of covered information as defined by Nevada law. We do not currently sell covered information. Send requests to <a href="mailto:team@thebluedotagency.com?subject=Nevada%20privacy%20request">team@thebluedotagency.com</a>.</p></Section>
  <Section title="9. Security"><p>We use administrative, technical, and organizational safeguards designed to protect personal information. No transmission or storage method is completely secure. Please use the contact information below if you believe information submitted to us has been compromised.</p></Section>
  <Section title="10. Children and External Links"><p>This website is intended for adults and is not directed to children under 13. We do not knowingly collect personal information from children under 13. External websites have their own privacy practices, which we do not control.</p></Section>
  <Section title="11. Changes"><p>We may update this notice as our services and practices change. The effective date above identifies the current version. Material changes will be communicated through the website or another appropriate channel.</p></Section>
  <Section title="12. Contact"><p>Questions and privacy requests may be directed to:</p><p>{contact}</p></Section>
</>}

function Terms(){return <>
  <p className="legal-kicker">Effective Date: September 3, 2026</p><h1>Terms of Service</h1>
  <p className="legal-lead">Employ AI, an S corporation doing business as The Blue Dot Agency, operates this website. In these terms, “The Blue Dot Agency,” “we,” and “us” mean Employ AI. These terms govern use of the website. A proposal, statement of work, order form, or other signed agreement governs paid client services and controls if it conflicts with these website terms.</p>
  <Section title="1. Website Use"><p>You may use this website for lawful personal or business evaluation purposes. You may not disrupt the site, attempt unauthorized access, introduce malicious code, scrape the site in a manner that impairs it, impersonate another person, or use the site to violate another person’s rights.</p></Section>
  <Section title="2. Information and No Guarantee"><p>Website content is general information and is not legal, tax, medical, financial, or other regulated professional advice. We work to keep the site accurate but do not promise that every item will always be complete, current, or error-free. Examples, portfolio work, and descriptions do not guarantee a particular business result.</p></Section>
  <Section title="3. AI-Assisted Chat"><p>The website chat may use artificial intelligence and automation. AI responses may be incomplete or inaccurate and are provided only for general information, routing, and scheduling. Do not rely on the chat for emergencies or regulated professional advice, and do not submit sensitive personal information through it.</p></Section>
  <Section title="4. Appointments and Communications"><p>Submitting a form or booking an appointment does not create a client relationship. A client relationship begins only when both parties enter a written agreement. If you separately consent to SMS, message frequency varies and message and data rates may apply. Reply STOP to stop or HELP for assistance. Marketing consent is not a condition of purchase.</p></Section>
  <Section title="5. Intellectual Property"><p>The website and its original content are owned by The Blue Dot Agency or used with permission and are protected by applicable intellectual-property laws. You may view and print reasonable portions for internal evaluation. You may not reproduce, sell, publish, modify, or commercially exploit website content without written permission.</p><h3>Material You Submit</h3><p>You retain ownership of material you submit. You give us a non-exclusive, worldwide, royalty-free license to host, copy, transmit, and use that material only as reasonably necessary to respond to your request, evaluate or provide requested services, operate the relevant feature, comply with law, and protect the parties’ rights. This license ends when the purpose is complete or the material is deleted, except for limited backups, legal records, and rights granted in a separate written client agreement. We will not sell your submitted material or use it publicly in a portfolio without separate permission.</p></Section>
  <Section title="6. Third-Party Services"><p>The website links to and uses services operated by third parties, including appointment and chat providers. Their services may be governed by separate terms. We are not responsible for third-party websites or services we do not control.</p></Section>
  <Section title="7. Purchases and Recurring Services"><p>This website does not currently enroll visitors in a subscription or free trial. Any future paid or recurring offer must disclose the price, billing frequency, renewal terms, cancellation method, and applicable refund terms before purchase. Paid agency work is governed by the written agreement presented for that engagement.</p></Section>
  <Section title="8. Disclaimer and Liability"><p>To the extent permitted by law, the website is provided on an “as available” basis without implied warranties. The Blue Dot Agency is not liable for indirect, incidental, special, consequential, or punitive damages arising solely from use of this informational website. Nothing in these terms excludes rights or liability that cannot legally be excluded.</p></Section>
  <Section title="9. Governing Law and Venue"><p>These website terms are governed by Nevada law, without regard to conflict-of-law principles. Unless a separate signed agreement provides otherwise, disputes concerning these website terms will be brought in a court of competent jurisdiction located in Clark County, Nevada. Each party retains any rights that applicable law does not permit these terms to waive.</p></Section>
  <Section title="10. Changes and Severability"><p>We may update these terms by posting a revised version with a new effective date. If a provision is found unenforceable, the remaining provisions remain in effect. Our failure to enforce a provision is not a waiver.</p></Section>
  <Section title="11. Contact"><p>Questions about these terms may be directed to:</p><p>{contact}</p></Section>
</>}

export function LegalPage({type}){const privacy=type==='privacy';return <div className="legal-page"><header className="legal-header"><a href="/" aria-label="Blue Dot Agency home"><img src="/assets/blue-dot/blue-dot-logo-exact.png" alt="The Blue Dot Agency"/></a><a href="/">Return to website</a></header><main className="legal-content"><p className="legal-draft">Working draft for lawyer review. Not approved legal advice.</p>{privacy?<PrivacyPolicy/>:<Terms/>}</main><footer className="legal-footer"><span>© 2026 The Blue Dot Agency</span><nav><a href="/privacy-policy">Privacy Policy</a><a href="/terms-and-conditions">Terms of Service</a></nav></footer></div>}
